import datetime
cur_date=datetime.datetime.now()
print(cur_date)
strf=cur_date.strftime("%Y-%B-%A")
print(strf)
strf=cur_date.strftime("%Y")
print("full format of year:",strf)
strf=cur_date.strftime("%y")
print("short format of year:",strf)
strf=cur_date.strftime("%B")
print("full format of month:",strf)
strf=cur_date.strftime("%b")
print("short format of month:",strf)
strf=cur_date.strftime("%A")
print("full format of day:",strf)
strf=cur_date.strftime("%a")
print("short format of day:",strf)
strf=cur_date.strftime("%w")
print("Weekday as a number 0-6, 0 is Sunday:",strf)
strf=cur_date.strftime("%W")
print("Week number of year, Monday as the first day of week, 00-53:",strf)
strf=cur_date.strftime("%U")
print("Week number of year, Sunday as the first day of week, 00-53:",strf)
strf=cur_date.strftime("%H")
print("24 hour format:",strf)
strf=cur_date.strftime("%I")
print("12 hour format:",strf)
strf=cur_date.strftime("%P")
print("AM / PM :",strf)
strf=cur_date.strftime("%M")
print("minutes:",strf)
strf=cur_date.strftime("%S")
print("seconds:",strf)
strf=cur_date.strftime("%f")
print("micro seconds:",strf)
strf=cur_date.strftime("%j")
print("Day number of year:",strf)
strf=cur_date.strftime("%x")
print("Current date:",strf)
strf=cur_date.strftime("%X")
print("current time:",strf)


